### PR TITLE
Actually create queues / topics during queue / topic create. Correct …

### PR DESCRIPTION
**Pull request by TiS**
…queue/topic naming.

This PR adds possibility to actually create queues and topics in Azure, if necessary.

It also gives some formatting to queue / topic names, replacing some commonly used in enqueue - but invalid in Azure Storage - characters.

### CODE REVIEW

**Comment by TiS** [comment]
@sylfabre - can you look at this one in your spare time?

FYI, I've got one more PR coming for your consideration. But that's another story.

**Comment by sylfabre** [comment]
@TiS I've updated the .travis.yml file, could you please rebase your PR, please?

**Comment by sylfabre** [comment]
@TiS I hope it'll fix this Travis issue

**Comment by TiS** [comment]
Yes, as it looks, it worked.

**Pull request merged**
